language: php

sudo: false

cache:
  directories:
    - node_modules
    - vendor

services:
    - redis-server

env:
  - ENJ_DATABASE=enjoin_test ENJ_USERNAME=enjoin_test ENJ_PASSWORD=enjoin_test

install:
  - npm install -g gulp
  - npm install
  - composer install

before_script:
  - mysql -e "CREATE DATABASE enjoin_test;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON enjoin_test.* TO enjoin_test@localhost IDENTIFIED BY 'enjoin_test';"
  - gulp create-tables

script: phpunit

php:
  - '5.5'
  - '5.6'
