site_name: Enjoin ORM
site_description: PHP Active Record ORM designed for Laravel

repo_url: https://github.com/mightydes/enjoin

pages:
- ['index.md', 'Installation']
- ['models/definition.md', 'Models', 'Definition']
